{% set name = "jupyterlab_iframe" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 01d729a12470aa9d1878f337a712d6f12065d5cefbd134b6d4e8e80c429eefa7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - nodejs >=16
    - yarn
    - hatchling
    - hatch-jupyter-builder
    - jupyterlab >=4,<5
  run:
    - python >=3.7
    - jupyterlab >=4,<5
    - requests >=2.22.0
    - tornado-proxy-handlers >=0.0.5

test:
  imports:
    - jupyterlab_iframe

about:
  home: http://github.com/timkpaine/jupyterlab_iframe
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: IFrame widgets for JupyterLab

  description: |
    IFrame widgets for JupyterLab
  dev_url: https://github.com/timkpaine/jupyterlab_iframe

extra:
  recipe-maintainers:
    - timkpaine
