{% set name = "jupyterlab_iframe" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dbba9a73552e2a8267be9a5e60ba7ce33e0b28d9ebc16789fb442403e26a2cfb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - nodejs
    - yarn
    - jupyter-packaging
    - jupyterlab >=3.0.0
  run:
    - python >=3.7
    - jupyterlab >=3.0.0
    - requests >=2.22.0
    - tornado >=6.0.0
    - tornado-proxy-handlers >=0.0.5

test:
  imports:
    - jupyterlab_iframe

about:
  home: http://github.com/timkpaine/jupyterlab_iframe
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: IFrame widgets for JupyterLab

  description: |
    IFrame widgets for JupyterLab
  dev_url: https://github.com/timkpaine/jupyterlab_iframe

extra:
  recipe-maintainers:
    - timkpaine
